name: TESTCI

on: 
  workflow_dispatch:
    inputs:
      chrome_access_code:
        description: Copy your chrome remote access code
        required: true
      pin:
        description: Enter your 6 numbers pin
        required: false
jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Run settting file
        run: |
          ./setting.ps1
          ${{ github.event.inputs.chrome_access_code }} -pin=${{ github.event.inputs.pin }}
      - name: Windows Server ready to go 
        run: sleep 86400
